title: Pod
description: Pod is an alternative launcher for Risk of Rain Modloader (RoRML).
logo: /assets/img/logo.png

project_links:
- zip_url: "https://gitlab.com/noneNA/pod/-/archive/master/pod-master.zip"
- flatpak: "https://none-na.github.io/pod-pages/"
- repository_url: "https://gitlab.com/noneNA/pod"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
