title: Pod
description: Pod is an alternative launcher for Risk of Rain Modloader (RoRML).
logo: /assets/img/logo.png

show_downloads: true
project_links:
- zip_url: "https://gitlab.com/noneNA/pod/-/archive/master/pod-master.zip"
- tar_url: "https://gitlab.com/noneNA/pod/-/archive/master/pod-master.tar.gz"
- flatpak: "https://none-na.github.io/pod-pages/"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
